defmodule GuardedStructFixtures.CrossFieldTest do
  @moduledoc """
  Tests the `GuardedStructFixtures.CrossField` fixture — covering:

    * `AuditedEvent` — `from:`, `on:`, `auto:`, `domain:`, `authorized_fields:`
    * `StrictEvent` — the `sub_field(..., enforce: true)` enforce-cascade pattern
  """

  use ExUnit.Case, async: true

  alias GuardedStructFixtures.CrossField

  describe "AuditedEvent (from / on / auto / domain)" do
    test "happy path: from: pulls actor_id; auto: mints event_id" do
      # All required fields present. `event.actor_id` is auto-pulled
      # from root via `from:`, `event.event_id` is generated by `auto:`.
      assert {:ok, ev} =
               CrossField.AuditedEvent.builder(%{
                 actor_id: "11111111-1111-1111-1111-111111111111",
                 account_type: "enterprise",
                 requested_by: "alice",
                 event: %{name: "did the thing", kind: "billing.refund"}
               })

      assert ev.event.actor_id == ev.actor_id
      assert is_binary(ev.event.event_id)
      assert String.length(ev.event.event_id) > 10
    end

    test "on: blocks build when the depended-on path is missing" do
      # ERROR REASON: `event.name` has `on: "root::actor_id"`, but we
      # omit `:actor_id` from the input → `on:` precondition fails.
      assert {:error, _} =
               CrossField.AuditedEvent.builder(%{
                 account_type: "enterprise",
                 requested_by: "alice",
                 event: %{name: "x", kind: "login"}
               })
    end

    test "validate(enum=...) rejects an out-of-set kind" do
      # ERROR REASON: `event.kind` derives say enum must be one of
      # [login, logout, data.read, billing.refund]. "totally.invented"
      # is not in the set → :enum validator fails.
      assert {:error, _} =
               CrossField.AuditedEvent.builder(%{
                 actor_id: "11111111-1111-1111-1111-111111111111",
                 account_type: "enterprise",
                 requested_by: "alice",
                 event: %{name: "x", kind: "totally.invented"}
               })
    end

    test "domain: rejects values outside the allowed account_type set" do
      # ERROR REASON: `:requested_by` has a domain rule pointing at
      # `account_type`, which must be one of [free, pro, enterprise].
      # "trial" is not in the set → :domain_parameters error.
      assert {:error, _} =
               CrossField.AuditedEvent.builder(%{
                 actor_id: "11111111-1111-1111-1111-111111111111",
                 account_type: "trial",
                 requested_by: "alice",
                 event: %{name: "x", kind: "login"}
               })
    end

    test "authorized_fields: true rejects unknown top-level keys" do
      # ERROR REASON: section has `authorized_fields: true`, so extra
      # keys that aren't declared as fields (`:hacker_added`) trigger
      # the :authorized_fields error.
      assert {:error, _} =
               CrossField.AuditedEvent.builder(%{
                 actor_id: "11111111-1111-1111-1111-111111111111",
                 account_type: "free",
                 requested_by: "alice",
                 event: %{name: "x", kind: "login"},
                 hacker_added: "value"
               })
    end
  end

  describe "StrictEvent (sub_field enforce-cascade pattern)" do
    test "happy path: all enforced inner fields supplied → build succeeds" do
      # `:kind` and `:body` are required by cascade (parent has
      # `enforce: true`, they have no default). Both supplied → ok.
      # `:trace_id` is `enforce: false`; `:retries` has `default: 0`.
      assert {:ok, ev} =
               CrossField.StrictEvent.builder(%{
                 source: "api",
                 payload: %{kind: "create", body: %{user_id: 1}}
               })

      assert ev.payload.kind == "create"
      assert ev.payload.trace_id == nil
      assert ev.payload.retries == 0
    end

    test "missing :kind (cascaded enforce) → :required_fields error" do
      # ERROR REASON: parent sub_field has `enforce: true`, so every
      # inner field without `default:` cascades to enforced. `:kind`
      # is omitted → :required_fields error from the Payload submodule.
      assert {:error, errs} =
               CrossField.StrictEvent.builder(%{
                 source: "api",
                 payload: %{body: %{x: 1}}
               })

      errs = List.wrap(errs)

      assert Enum.any?(errs, fn err ->
               err[:action] == :required_fields or
                 (is_map(err[:errors]) and err[:errors][:action] == :required_fields)
             end)
    end

    test "missing :body (cascaded enforce) → required error" do
      # ERROR REASON: same cascade as the :kind test — `:body` has no
      # default, so the parent's `enforce: true` makes it required.
      assert {:error, _} =
               CrossField.StrictEvent.builder(%{
                 source: "api",
                 payload: %{kind: "create"}
               })
    end

    test "missing :retries is FINE — `default:` opts it out of the cascade" do
      # `:retries` has `default: 0`, which short-circuits the cascade
      # (the codegen treats "has default" as "opted-out of enforce").
      # Build succeeds; the default is applied.
      assert {:ok, ev} =
               CrossField.StrictEvent.builder(%{
                 source: "api",
                 payload: %{kind: "create", body: %{}}
               })

      assert ev.payload.retries == 0
    end

    test "missing :trace_id is FINE — `enforce: false` opts it out explicitly" do
      # `:trace_id` is marked `enforce: false`, the EXPLICIT way to opt
      # out of the parent's enforce cascade. Build succeeds; value is nil.
      assert {:ok, _} =
               CrossField.StrictEvent.builder(%{
                 source: "api",
                 payload: %{kind: "create", body: %{}}
               })
    end

    test "missing :payload (the parent sub_field itself) → required error" do
      # ERROR REASON: the sub_field `:payload` is itself declared
      # `enforce: true`, so omitting it entirely fails at the OUTER
      # level (the StrictEvent's own enforce_keys list), independently
      # of the cascade behavior inside it.
      assert {:error, _} = CrossField.StrictEvent.builder(%{source: "api"})
    end

    test "inner submodule reports the cascade in its own enforce_keys/0" do
      # Regression lock for the cascade: the auto-generated Payload
      # submodule must list :kind and :body as enforced (cascade hit),
      # but NOT :retries (default opts out) or :trace_id (explicit opt out).
      keys = CrossField.StrictEvent.Payload.enforce_keys()
      assert :kind in keys
      assert :body in keys
      refute :retries in keys
      refute :trace_id in keys
    end
  end
end
